//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.0.0-alpha08-SNAPSHOT'.
//

public sealed class Gravity(
  public val rawValue: String
) {
  public companion object {

    /**
     * Returns [Gravity] matched with the specified [rawValue].
     */
    public fun safeValueOf(rawValue: String): Gravity = when(rawValue) {
      "TOP" -> TOP
      "top" -> top
      "BOTTOM" -> BOTTOM
      "LEFT" -> LEFT
      "RIGHT" -> RIGHT
      else -> UNKNOWN__(rawValue)
    }
  }

  public object TOP : Gravity(rawValue = "TOP")

  @Deprecated(message = "No longer supported")
  public object top : Gravity(rawValue = "top")

  public object BOTTOM : Gravity(rawValue = "BOTTOM")

  public object LEFT : Gravity(rawValue = "LEFT")

  public object RIGHT : Gravity(rawValue = "RIGHT")

  /**
   * An enum value that wasn't known at compile time.
   */
  public class UNKNOWN__(rawValue: String) : Gravity(rawValue = rawValue)
}
